// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog.sql

package db

import (
	"context"
)

const createBlogPost = `-- name: CreateBlogPost :exec
INSERT INTO blog_posts (slug, title, summary, category, date, body)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBlogPostParams struct {
	Slug     string
	Title    string
	Summary  string
	Category string
	Date     string
	Body     string
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) error {
	_, err := q.db.ExecContext(ctx, createBlogPost,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Category,
		arg.Date,
		arg.Body,
	)
	return err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
SELECT slug, title, summary, category, date, body, created_at, updated_at FROM blog_posts WHERE slug = ? LIMIT 1
`

func (q *Queries) GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error) {
	row := q.db.QueryRowContext(ctx, getBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Category,
		&i.Date,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT slug, title, summary, category, date, created_at, updated_at
FROM blog_posts
ORDER BY date DESC
`

type ListBlogPostsRow struct {
	Slug      string
	Title     string
	Summary   string
	Category  string
	Date      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListBlogPosts(ctx context.Context) ([]ListBlogPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogPostsRow
	for rows.Next() {
		var i ListBlogPostsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Category,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogPost = `-- name: UpdateBlogPost :exec
UPDATE blog_posts
SET title = ?, summary = ?, category = ?, date = ?, body = ?, updated_at = datetime('now')
WHERE slug = ?
`

type UpdateBlogPostParams struct {
	Title    string
	Summary  string
	Category string
	Date     string
	Body     string
	Slug     string
}

func (q *Queries) UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) error {
	_, err := q.db.ExecContext(ctx, updateBlogPost,
		arg.Title,
		arg.Summary,
		arg.Category,
		arg.Date,
		arg.Body,
		arg.Slug,
	)
	return err
}

const upsertBlogPost = `-- name: UpsertBlogPost :exec
INSERT INTO blog_posts (slug, title, summary, category, date, body, updated_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
    title      = excluded.title,
    summary    = excluded.summary,
    category   = excluded.category,
    date       = excluded.date,
    body       = excluded.body,
    updated_at = excluded.updated_at
`

type UpsertBlogPostParams struct {
	Slug     string
	Title    string
	Summary  string
	Category string
	Date     string
	Body     string
}

func (q *Queries) UpsertBlogPost(ctx context.Context, arg UpsertBlogPostParams) error {
	_, err := q.db.ExecContext(ctx, upsertBlogPost,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Category,
		arg.Date,
		arg.Body,
	)
	return err
}
