// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type BlogPost struct {
	Slug      string
	Title     string
	Summary   string
	Category  string
	Date      string
	Body      string
	CreatedAt string
	UpdatedAt string
}

type ClientUser struct {
	ID            string
	Name          string
	Email         string
	PasswordHash  string
	ProjectStatus string
}

type GeoCache struct {
	Prefix      string
	CountryCode string
	City        string
	Lat         float64
	Lon         float64
	CreatedAt   string
}

type ProposalLead struct {
	ID          string
	Name        string
	Email       string
	Company     sql.NullString
	ProjectType string
	Budget      sql.NullString
	Timeline    sql.NullString
	Details     string
	CreatedAt   string
}

type Visit struct {
	ID          int64
	VisitorHash string
	CountryCode string
	City        string
	Lat         float64
	Lon         float64
	Path        string
	CreatedAt   string
}
