// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposal.sql

package db

import (
	"context"
	"database/sql"
)

const createProposalLead = `-- name: CreateProposalLead :exec
INSERT INTO proposal_leads (id, name, email, company, project_type, budget, timeline, details, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateProposalLeadParams struct {
	ID          string
	Name        string
	Email       string
	Company     sql.NullString
	ProjectType string
	Budget      sql.NullString
	Timeline    sql.NullString
	Details     string
}

func (q *Queries) CreateProposalLead(ctx context.Context, arg CreateProposalLeadParams) error {
	_, err := q.db.ExecContext(ctx, createProposalLead,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Company,
		arg.ProjectType,
		arg.Budget,
		arg.Timeline,
		arg.Details,
	)
	return err
}

const listProposalLeads = `-- name: ListProposalLeads :many
SELECT id, name, email, company, project_type, budget, timeline, details, created_at FROM proposal_leads ORDER BY created_at DESC
`

func (q *Queries) ListProposalLeads(ctx context.Context) ([]ProposalLead, error) {
	rows, err := q.db.QueryContext(ctx, listProposalLeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProposalLead
	for rows.Next() {
		var i ProposalLead
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.ProjectType,
			&i.Budget,
			&i.Timeline,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
