// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT OR IGNORE INTO client_users (id, name, email, password_hash, project_status)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID            string
	Name          string
	Email         string
	PasswordHash  string
	ProjectStatus string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.ProjectStatus,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, project_status FROM client_users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (ClientUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.ProjectStatus,
	)
	return i, err
}
