// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package db

import (
	"context"
)

const countCountriesSince = `-- name: CountCountriesSince :one
SELECT COUNT(DISTINCT country_code) FROM visits
WHERE created_at >= datetime('now', ?) AND country_code <> ''
`

func (q *Queries) CountCountriesSince(ctx context.Context, datetime interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCountriesSince, datetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisitorsSince = `-- name: CountVisitorsSince :one
SELECT COUNT(DISTINCT visitor_hash) FROM visits WHERE created_at >= datetime('now', ?)
`

func (q *Queries) CountVisitorsSince(ctx context.Context, datetime interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisitorsSince, datetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisitsSince = `-- name: CountVisitsSince :one
SELECT COUNT(*) FROM visits WHERE created_at >= datetime('now', ?)
`

func (q *Queries) CountVisitsSince(ctx context.Context, datetime interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisitsSince, datetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVisitsBefore = `-- name: DeleteVisitsBefore :exec
DELETE FROM visits WHERE created_at < datetime('now', ?)
`

func (q *Queries) DeleteVisitsBefore(ctx context.Context, datetime interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteVisitsBefore, datetime)
	return err
}

const getGeoCache = `-- name: GetGeoCache :one
SELECT prefix, country_code, city, lat, lon, created_at
FROM geo_cache
WHERE prefix = ? LIMIT 1
`

func (q *Queries) GetGeoCache(ctx context.Context, prefix string) (GeoCache, error) {
	row := q.db.QueryRowContext(ctx, getGeoCache, prefix)
	var i GeoCache
	err := row.Scan(
		&i.Prefix,
		&i.CountryCode,
		&i.City,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentVisits = `-- name: ListRecentVisits :many
SELECT visitor_hash, country_code, city, lat, lon, path, created_at
FROM visits
WHERE created_at >= datetime('now', ?) AND country_code <> ''
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentVisitsParams struct {
	Datetime interface{}
	Limit    int64
}

type ListRecentVisitsRow struct {
	VisitorHash string
	CountryCode string
	City        string
	Lat         float64
	Lon         float64
	Path        string
	CreatedAt   string
}

func (q *Queries) ListRecentVisits(ctx context.Context, arg ListRecentVisitsParams) ([]ListRecentVisitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentVisits, arg.Datetime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentVisitsRow
	for rows.Next() {
		var i ListRecentVisitsRow
		if err := rows.Scan(
			&i.VisitorHash,
			&i.CountryCode,
			&i.City,
			&i.Lat,
			&i.Lon,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVisit = `-- name: RecordVisit :exec

INSERT INTO visits (visitor_hash, country_code, city, lat, lon, path)
VALUES (?, ?, ?, ?, ?, ?)
`

type RecordVisitParams struct {
	VisitorHash string
	CountryCode string
	City        string
	Lat         float64
	Lon         float64
	Path        string
}

// A visit whose address could not be geolocated is still a page view: it counts
// toward views, visitors and paths, and is stored with an empty country_code.
// The three queries that feed the map and the country list filter those out,
// because a dot at 0,0 is the Gulf of Guinea and a blank flag is not a country.
func (q *Queries) RecordVisit(ctx context.Context, arg RecordVisitParams) error {
	_, err := q.db.ExecContext(ctx, recordVisit,
		arg.VisitorHash,
		arg.CountryCode,
		arg.City,
		arg.Lat,
		arg.Lon,
		arg.Path,
	)
	return err
}

const topCountriesSince = `-- name: TopCountriesSince :many
SELECT country_code, COUNT(*) AS visits
FROM visits
WHERE created_at >= datetime('now', ?) AND country_code <> ''
GROUP BY country_code
ORDER BY visits DESC, country_code ASC
LIMIT ?
`

type TopCountriesSinceParams struct {
	Datetime interface{}
	Limit    int64
}

type TopCountriesSinceRow struct {
	CountryCode string
	Visits      int64
}

func (q *Queries) TopCountriesSince(ctx context.Context, arg TopCountriesSinceParams) ([]TopCountriesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topCountriesSince, arg.Datetime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopCountriesSinceRow
	for rows.Next() {
		var i TopCountriesSinceRow
		if err := rows.Scan(&i.CountryCode, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPathsSince = `-- name: TopPathsSince :many
SELECT path, COUNT(*) AS visits
FROM visits
WHERE created_at >= datetime('now', ?)
GROUP BY path
ORDER BY visits DESC, path ASC
LIMIT ?
`

type TopPathsSinceParams struct {
	Datetime interface{}
	Limit    int64
}

type TopPathsSinceRow struct {
	Path   string
	Visits int64
}

func (q *Queries) TopPathsSince(ctx context.Context, arg TopPathsSinceParams) ([]TopPathsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topPathsSince, arg.Datetime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPathsSinceRow
	for rows.Next() {
		var i TopPathsSinceRow
		if err := rows.Scan(&i.Path, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGeoCache = `-- name: UpsertGeoCache :exec
INSERT INTO geo_cache (prefix, country_code, city, lat, lon)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(prefix) DO UPDATE SET
    country_code = excluded.country_code,
    city         = excluded.city,
    lat          = excluded.lat,
    lon          = excluded.lon
`

type UpsertGeoCacheParams struct {
	Prefix      string
	CountryCode string
	City        string
	Lat         float64
	Lon         float64
}

func (q *Queries) UpsertGeoCache(ctx context.Context, arg UpsertGeoCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertGeoCache,
		arg.Prefix,
		arg.CountryCode,
		arg.City,
		arg.Lat,
		arg.Lon,
	)
	return err
}
